In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import pandas as pd
## read from existing results :
#/home/hmoradis/UQA/Julien/Task22-our_MTL/bart_based_emotion_paper_run3/
df_all = pd.read_csv("MRC Eval/EPOCH3BARTALL.csv",sep=',')
#df_all = df_all.iloc[:, 12:]
print(df_all.columns)
df_all

Index(['Unnamed: 0.1', 'Unnamed: 0', 'qid', 'OU model2 answer span',
       'OU model2 start', 'OU model2 end', 'OU model2 score',
       'SA model2 answer span', 'SA model2 start', 'SA model2 end',
       'SA model2 score', 'OU model4 answer span', 'OU model4 start',
       'OU model4 end', 'OU model4 score', 'SA model4 answer span',
       'SA model4 start', 'SA model4 end', 'SA model4 score',
       'OU electra answer span', 'OU electra start', 'OU electra end',
       'OU electra score', 'SA electra answer span', 'SA electra start',
       'SA electra end', 'SA electra score', 'OU roberta answer span',
       'OU roberta start', 'OU roberta end', 'OU roberta score',
       'SA roberta answer span', 'SA roberta start', 'SA roberta end',
       'SA roberta score', 'OU retro answer span', 'SA retro answer span',
       'OU sgnet answer span', 'SA sgnet answer span', 'context', 'uq',
       'labels', 'suggested aq', 'predicted_labels'],
      dtype='object')

,Unnamed: 0.1,Unnamed: 0,qid,OU model2 answer span,OU model2 start,OU model2 end,OU model2 score,SA model2 answer span,SA model2 start,SA model2 end,...,SA roberta score,OU retro answer span,SA retro answer span,OU sgnet answer span,SA sgnet answer span,context,uq,labels,suggested aq,predicted_labels
0,0,0,5ad39d53604f3c001a3fe8d1,The Normans,0,11,2.337817e-04,The Normans,0,11,...,8.349488e-01,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th ce...,E
1,1,1,5ad39d53604f3c001a3fe8d2,"Normandy,",136,146,5.196336e-07,10th and 11th centuries,93,117,...,2.490300e-01,<No Answer>. The question is not answerable ac...,10th and 11th centuries,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,What is France a region of?,I,When did the Normans start to move to Normandy?,I
2,2,2,5ad39d53604f3c001a3fe8d3,West Francia.,556,570,1.021575e-06,swear fealty to King Charles III of West Fran...,324,374,...,3.670775e-01,<No Answer>. The question is not answerable ac...,swear fealty to king charles iii of west francia,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,Who did King Charles III swear fealty to?,I,What did the Normans agree to do?,I
3,3,3,5ad39d53604f3c001a3fe8d4,"first half of the 10th century,",652,684,1.761726e-09,"first half of the 10th century,",652,684,...,5.691159e-01,<No Answer>. The question is not answerable ac...,first half of the 10th century,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,When did the Frankish identity emerge?,E,When did the Normans start to develop?,I
4,4,4,5ad3a266604f3c001a3fea27,"political, cultural and military",30,63,1.606901e-07,"political, cultural and military",30,63,...,8.276052e-07,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,"political, cultural and military",p,"The Norman dynasty had a major political, cult...",What type of major impact did the Norman dynas...,X,What type of major impact did the Norman dynas...,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5940,5940,5940,5ad28a57d7d075001a4299b3,nonconservative forces,187,210,1.125980e-08,nonconservative forces act to change the inte...,187,261,...,4.124932e-02,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The connection between macroscopic nonconserva...,What does not change macroscopic closed systems?,N,What does change macroscopic closed systems?,N
5941,5941,5941,5ad28ad0d7d075001a4299cc,newton:,69,77,5.952701e-07,"expressing aircraft weight, jet thrust,",512,552,...,8.955895e-02,<No Answer>. The question is not answerable ac...,"expressing aircraft weight, jet thrust, bicycl...",NaN,NaN,"The pound-force has a metric counterpart, less...",What does not have a metric counterpart?,N,What is the kilogram-force used for?,I
5942,5942,5942,5ad28ad0d7d075001a4299cd,kilogram-force,81,96,1.338633e-07,kilogram-force,81,96,...,5.207127e-01,<No Answer>. The question is not answerable ac...,the kilogram-force,NaN,NaN,"The pound-force has a metric counterpart, less...",What is the force exerted by standard gravity ...,E,What is the force exerted by standard gravity ...,E
5943,5943,5943,5ad28ad0d7d075001a4299ce,kilogram-force,194,209,4.873671e-08,"expressing aircraft weight, jet thrust,",512,552,...,8.955895e-02,<No Answer>. The question is not answerable ac...,"expressing aircraft weight, jet thrust, bicycl...",NaN,NaN,"The pound-force has a metric counterpart, less...",What force leads to a commonly used unit of mass?,E,What is the kilogram-force used for?,I
5944,5944,5944,5ad28ad0d7d075001a4299cf,kilogram-force,81,96,1.914169e-08,the force exerted by standard gravity on one ...,127,190,...,7.033049e-01,<No Answer>. The question is not answerable ac...,the force exerted by standard gravity on one k...,NaN,NaN,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What is the kilogram-force?,I

In [3]:
### for unanswerability
### for unanswerability
OU_model2 = []
OU_model4 = []
OU_electra = []
OU_roberta = []
OU_sgnet = []
OU_retro = []

SA_model2 = []
SA_model4 = []
SA_electra = []
SA_roberta = []
SA_sgnet = []
SA_retro = []
df_all['SA retro answer span'] = df_all['SA retro answer span'].astype(str)
for index, row in df_all.iterrows():
    if index % 100000 == 0:
        print(index)
    
    OU_question_sgnet = row['OU sgnet answer span']
    OU_question_retro = row['OU retro answer span']
    OU_questionS_model2 = row['OU model2 score']
    OU_questionS_model4 = row['OU model4 score']
    OU_questionS_electra = row['OU electra score']
    OU_questionS_roberta = row['OU roberta score']
    
    SA_question_sgnet = row['SA sgnet answer span']
    SA_question_retro = row['SA retro answer span']
    SA_questionS_model2 = row['SA model2 score']
    SA_questionS_model4 = row['SA model4 score']
    SA_questionS_electra = row['SA electra score']
    SA_questionS_roberta = row['SA roberta score']
    
    if OU_questionS_model2 <= 0.096476303 : # unanswerablity checking
        OU_model2.append(0)  #unanswerable
    else:
        OU_model2.append(1)  #answerable
    
    if OU_questionS_model4 <= 0.15272566:
        OU_model4.append(0) #unanswerable
    else:
        OU_model4.append(1) #answerable
    
    if OU_questionS_electra <= 0.141489303:
        OU_electra.append(0) #unanswerable
    else:
        OU_electra.append(1) #answerable
        
    if OU_questionS_roberta <= 0.063691394:
        OU_roberta.append(0) #unanswerable
    else: 
        OU_roberta.append(1) #answerable
    
    if OU_question_sgnet == "": 
        OU_sgnet.append(0) #unanswerable
    else:
        OU_sgnet.append(1) #answerable
        
    if OU_question_retro == "" or OU_question_retro.startswith("[SEP]") or OU_question_retro == "'" or OU_question_retro == "," or OU_question_retro == "<No Answer>. The question is not answerable according to the context." or OU_question_retro == "<unk>=0" :
        OU_retro.append(0) #unanswerable
    else:
        OU_retro.append(1) #answerable
        
        
    if SA_questionS_model2 <= 0.096476303 : # unanswerablity checking
        SA_model2.append(0)  #unanswerable
    else:
        SA_model2.append(1)  #answerable
    
    if SA_questionS_model4 <= 0.15272566:
        SA_model4.append(0) #unanswerable
    else:
        SA_model4.append(1) #answerable
    
    if SA_questionS_electra <= 0.141489303:
        SA_electra.append(0) #unanswerable
    else:
        SA_electra.append(1) #answerable
        
    if SA_questionS_roberta <= 0.063691394:
        SA_roberta.append(0) #unanswerable
    else: 
        SA_roberta.append(1) #answerable
    
    if SA_question_sgnet == "": 
        SA_sgnet.append(0) #unanswerable
    else:
        SA_sgnet.append(1) #answerable
        
    if SA_question_retro == "" or SA_question_retro.startswith("[SEP]") or SA_question_retro == "'" or SA_question_retro == "," or SA_question_retro == "<No Answer>. The question is not answerable according to the context." or SA_question_retro == "<unk>=0" :
        SA_retro.append(0) #unanswerable
    else:
        SA_retro.append(1) #answerable

df_all['OU_unanswerability_model2'] = OU_model2
df_all['OU_unanswerability_model4'] = OU_model4
df_all['OU_unanswerability_electra'] = OU_electra
df_all['OU_unanswerability_roberta'] = OU_roberta
df_all['OU_unanswerability_sgnet'] = OU_sgnet
df_all['OU_unanswerability_retro'] = OU_retro


df_all['SA_unanswerability_model2'] = SA_model2
df_all['SA_unanswerability_model4'] = SA_model4
df_all['SA_unanswerability_electra'] = SA_electra
df_all['SA_unanswerability_roberta'] = SA_roberta
df_all['SA_unanswerability_sgnet'] = SA_sgnet
df_all['SA_unanswerability_retro'] = SA_retro

new_column_order = [
       'qid', 'context', 'uq', 'labels', 'suggested aq',
       'OU model2 answer span', 'OU model2 start', 'OU model2 end','OU model2 score', 'OU_unanswerability_model2',
       'SA model2 answer span', 'SA model2 start', 'SA model2 end', 'SA model2 score', 'SA_unanswerability_model2',
       'OU model4 answer span', 'OU model4 start', 'OU model4 end', 'OU model4 score', 'OU_unanswerability_model4',
       'SA model4 answer span', 'SA model4 start', 'SA model4 end', 'SA model4 score', 'SA_unanswerability_model4',
       'OU electra answer span', 'OU electra start', 'OU electra end', 'OU electra score', 'OU_unanswerability_electra',
       'SA electra answer span', 'SA electra start', 'SA electra end', 'SA electra score','SA_unanswerability_electra',
       'OU roberta answer span', 'OU roberta start', 'OU roberta end','OU roberta score', 'OU_unanswerability_roberta',
       'SA roberta answer span', 'SA roberta start', 'SA roberta end', 'SA roberta score', 'SA_unanswerability_roberta',
       'OU retro answer span','OU_unanswerability_retro' ,'SA retro answer span', 'SA_unanswerability_retro',
       'OU sgnet answer span','OU_unanswerability_sgnet' ,'SA sgnet answer span', 'SA_unanswerability_sgnet']

df_all = df_all[new_column_order]


df_all

0

,qid,context,uq,labels,suggested aq,OU model2 answer span,OU model2 start,OU model2 end,OU model2 score,OU_unanswerability_model2,...,SA roberta score,SA_unanswerability_roberta,OU retro answer span,OU_unanswerability_retro,SA retro answer span,SA_unanswerability_retro,OU sgnet answer span,OU_unanswerability_sgnet,SA sgnet answer span,SA_unanswerability_sgnet
0,5ad39d53604f3c001a3fe8d1,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th ce...,The Normans,0,11,2.337817e-04,0,...,8.349488e-01,1,<No Answer>. The question is not answerable ac...,0,<No Answer>. The question is not answerable ac...,0,NaN,1,NaN,1
1,5ad39d53604f3c001a3fe8d2,The Normans (Norman: Nourmands; French: Norman...,What is France a region of?,I,When did the Normans start to move to Normandy?,"Normandy,",136,146,5.196336e-07,0,...,2.490300e-01,1,<No Answer>. The question is not answerable ac...,0,10th and 11th centuries,1,NaN,1,NaN,1
2,5ad39d53604f3c001a3fe8d3,The Normans (Norman: Nourmands; French: Norman...,Who did King Charles III swear fealty to?,I,What did the Normans agree to do?,West Francia.,556,570,1.021575e-06,0,...,3.670775e-01,1,<No Answer>. The question is not answerable ac...,0,swear fealty to king charles iii of west francia,1,NaN,1,NaN,1
3,5ad39d53604f3c001a3fe8d4,The Normans (Norman: Nourmands; French: Norman...,When did the Frankish identity emerge?,E,When did the Normans start to develop?,"first half of the 10th century,",652,684,1.761726e-09,0,...,5.691159e-01,1,<No Answer>. The question is not answerable ac...,0,first half of the 10th century,1,NaN,1,NaN,1
4,5ad3a266604f3c001a3fea27,"The Norman dynasty had a major political, cult...",What type of major impact did the Norman dynas...,X,What type of major impact did the Norman dynas...,"political, cultural and military",30,63,1.606901e-07,0,...,8.276052e-07,0,<No Answer>. The question is not answerable ac...,0,<No Answer>. The question is not answerable ac...,0,"political, cultural and military",1,p,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5940,5ad28a57d7d075001a4299b3,The connection between macroscopic nonconserva...,What does not change macroscopic closed systems?,N,What does change macroscopic closed systems?,nonconservative forces,187,210,1.125980e-08,0,...,4.124932e-02,0,<No Answer>. The question is not answerable ac...,0,<No Answer>. The question is not answerable ac...,0,NaN,1,NaN,1
5941,5ad28ad0d7d075001a4299cc,"The pound-force has a metric counterpart, less...",What does not have a metric counterpart?,N,What is the kilogram-force used for?,newton:,69,77,5.952701e-07,0,...,8.955895e-02,1,<No Answer>. The question is not answerable ac...,0,"expressing aircraft weight, jet thrust, bicycl...",1,NaN,1,NaN,1
5942,5ad28ad0d7d075001a4299cd,"The pound-force has a metric counterpart, less...",What is the force exerted by standard gravity ...,E,What is the force exerted by standard gravity ...,kilogram-force,81,96,1.338633e-07,0,...,5.207127e-01,1,<No Answer>. The question is not answerable ac...,0,the kilogram-force,1,NaN,1,NaN,1
5943,5ad28ad0d7d075001a4299ce,"The pound-force has a metric counterpart, less...",What force leads to a commonly used unit of mass?,E,What is the kilogram-force used for?,kilogram-force,194,209,4.873671e-08,0,...,8.955895e-02,1,<No Answer>. The question is not answerable ac...,0,"expressing aircraft weight, jet thrust, bicycl...",1,NaN,1,NaN,1
5944,5ad28ad0d7d075001a4299cf,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What is the kilogram-force?,kilogram-force,81,96,1.914169e-08,0,...,7.033049e-01,1,<No Answer>. The question is not answerable ac...,0,the force exerted by standard gravity on one k...,1,NaN,1,NaN,1

In [4]:
import pandas as pd
from tqdm import tqdm

# Define an empty list to hold the rows
rows = []

# Iterate through the DataFrame using iterrows
for index, row in tqdm(df_all.iterrows(), total=df_all.shape[0], desc="Processing rows"):
    if index % 100000 == 0: 
        print(index)

    qid = row['qid']
    context = row['context']
    OU_question = row['uq']
    label = row['labels']
    SA_question = row['suggested aq']

    model_data = [
        ('model 2', row['OU_unanswerability_model2'], row['SA_unanswerability_model2']),
        ('model 4', row['OU_unanswerability_model4'], row['SA_unanswerability_model4']),
        ('electra', row['OU_unanswerability_electra'], row['SA_unanswerability_electra']),
        ('roberta', row['OU_unanswerability_roberta'], row['SA_unanswerability_roberta']),
        ('sgnet', row['OU_unanswerability_sgnet'], row['SA_unanswerability_sgnet']),
        ('retro', row['OU_unanswerability_retro'], row['SA_unanswerability_retro'])]

    for model_name, OU_un, SA_un in model_data:
        row_data = [qid, context, OU_question, label, SA_question, OU_un , SA_un, model_name]
        rows.append(row_data)

# Convert the list of rows to a DataFrame
result_df = pd.DataFrame(rows, columns=['qid', 'context', 'uq', 'label', 'suggested aq', 
                                        'unanswerability on UQ question', 'unanswerability on SA question','model name'])
# result_df.to_csv('/home/hmoradis/UQA/Julien/Task21-Bart_no_Label/Evaluation/unanswerability_results_bart_no_label.csv')

result_df

Processing rows:  54%|████████████████████████████████▏                          | 3239/5945 [00:00<00:00, 16641.91it/s]

0

Processing rows: 100%|███████████████████████████████████████████████████████████| 5945/5945 [00:00<00:00, 17354.45it/s]

,qid,context,uq,label,suggested aq,unanswerability on UQ question,unanswerability on SA question,model name
0,5ad39d53604f3c001a3fe8d1,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th ce...,0,1,model 2
1,5ad39d53604f3c001a3fe8d1,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th ce...,0,1,model 4
2,5ad39d53604f3c001a3fe8d1,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th ce...,0,0,electra
3,5ad39d53604f3c001a3fe8d1,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th ce...,0,1,roberta
4,5ad39d53604f3c001a3fe8d1,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th ce...,1,1,sgnet
...,...,...,...,...,...,...,...,...
35665,5ad28ad0d7d075001a4299cf,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What is the kilogram-force?,0,1,model 4
35666,5ad28ad0d7d075001a4299cf,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What is the kilogram-force?,0,1,electra
35667,5ad28ad0d7d075001a4299cf,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What is the kilogram-force?,0,1,roberta
35668,5ad28ad0d7d075001a4299cf,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What is the kilogram-force?,1,1,sgnet
35669,5ad28ad0d7d075001a4299cf,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What is the kilogram-force?,0,1,retro

In [5]:
import pandas as pd

# Group by 'qid' and 'potential_UQ question'
grouped = result_df.groupby('qid')

# Initialize an empty list to hold the result
result_list = []
                                      
# Iterate over each group
for name, group in grouped:
    
    model_name_list = []
    sw = True
    qid = name  # unpack the group name
    
    # Assume that context, original_question, and original_answer_span are the same for each group
    context = group.iloc[0]['context']
    UQ_question = group.iloc[0]['uq']
    lebel = group.iloc[0]['label']
    SA_question = group.iloc[0]['suggested aq']
    
    
    # Iterate through each row in the group
    for index, row in group.iterrows():
        UQ_un = row['unanswerability on UQ question']
        SA_un = row['unanswerability on SA question']
        #### New eval (1,0,0) for model2,model4,electra,roberta AND (1,0) for retro and sgnet   
        model_n = row['model name']
        if UQ_un == 0 : ### unanswerable question in dev set should be labeled as an unanswerable question
            if SA_un == 1 :  ## suggested question should be answerable
                if row['model name'] not in model_name_list:
                    model_name_list.append(row['model name'])
    
    # Add the result to the list
    result_list.append({
        'qid': qid,
        'context': context,
        'UQ_question': UQ_question,
        'label': label,
        'SA_question': SA_question,
        'model_name_list': model_name_list,
        'len': len(model_name_list)
    })


# Create a new DataFrame from the result list
new_df = pd.DataFrame(result_list)
# new_df.to_csv('/home/hmoradis/UQA/Julien/Task21-Bart_no_Label/Evaluation/evalresult01-bart_no_label.csv')
# Display the new DataFrame
display(new_df)

,qid,context,UQ_question,label,SA_question,model_name_list,len
0,5a0c6698f5590b0018dab3e4,The Amazon rainforest (Portuguese: Floresta Am...,Amazonia or the Amazon jungle are no longer us...,N,The Amazonia or the Amazon jungle are no longe...,[],0
1,5a0c6698f5590b0018dab3e5,The Amazon rainforest (Portuguese: Floresta Am...,What covers most of the Amazon basin of Centra...,N,What covers most of the Amazon basin of South ...,"[model 4, roberta, retro]",3
2,5a0c6698f5590b0018dab3e6,The Amazon rainforest (Portuguese: Floresta Am...,"201,000,000 sq mi of rainforest cover what?",N,How many sq mi of rainforest cover what?,"[model 2, model 4, electra, roberta]",4
3,5a0c6698f5590b0018dab3e7,The Amazon rainforest (Portuguese: Floresta Am...,Nineteen nations have what in this region?,N,How many nations have what in this region?,"[model 2, model 4, electra, roberta, retro]",5
4,5a0c6698f5590b0018dab3e8,The Amazon rainforest (Portuguese: Floresta Am...,The Amazon represents less than half of the pl...,N,The Amazon represents less than half of the pl...,[],0
...,...,...,...,...,...,...,...
5940,5ad572b15b96ef001a10af06,"In 1967, Manuel Blum developed an axiomatic co...",Who developed an axiomatic complexity theory b...,N,Who developed an axiomatic complexity theory b...,"[model 2, model 4, electra, roberta, retro]",5
5941,5ad572b15b96ef001a10af07,"In 1967, Manuel Blum developed an axiomatic co...","Who is responsible for the so-called, speed-up...",N,"Who is responsible for the so-called, speed-up...","[model 2, model 4, electra, roberta, retro]",5
5942,5ad572b15b96ef001a10af08,"In 1967, Manuel Blum developed an axiomatic co...",Who proved that these exist practical relevant...,N,Who proved that these exist practical relevant...,"[model 2, model 4, electra, roberta, retro]",5
5943,5ad572b15b96ef001a10af09,"In 1967, Manuel Blum developed an axiomatic co...","Who wrote the paper ""Reductibility Among Combi...",N,"Who wrote the paper ""Reducibility Among Combin...","[model 2, model 4, electra, roberta, retro]",5
5944,5ad572b15b96ef001a10af0a,"In 1967, Manuel Blum developed an axiomatic co...",What book featured 25 diverse comninatorial an...,N,What book featured 21 diverse comninatorial an...,"[model 2, model 4, roberta]",3

In [6]:
conditions = [
    ('len >= 1', new_df['len'] >= 1),
    ('len >= 2', new_df['len'] >= 2),
    ('len >= 3', new_df['len'] >= 3),
    ('len >= 4', new_df['len'] >= 4),
    ('len >= 5', new_df['len'] >= 5),
    ('len >= 6', new_df['len'] >= 6),
    ('len == 1', new_df['len'] == 1),
    ('len == 2', new_df['len'] == 2),
    ('len == 3', new_df['len'] == 3),
    ('len == 4', new_df['len'] == 4),
    ('len == 5', new_df['len'] == 5),
    ('len == 6', new_df['len'] == 6),
]

# Initialize an empty dictionary to hold the results
condition_counts = {}

# Iterate over each condition
for condition_name, condition in conditions:
    # Filter the DataFrame based on the current condition
    filtered_df = new_df[condition]
    
    # Count the number of records that meet the condition
    count = filtered_df.shape[0]
    
    # Store the count in the dictionary
    condition_counts[condition_name] = count

# Display the counts for each condition
for condition_name, count in condition_counts.items():
    print(f"Number of records where {condition_name}: {count}")

Number of records where len >= 1: 4360
Number of records where len >= 2: 3783
Number of records where len >= 3: 3226
Number of records where len >= 4: 2581
Number of records where len >= 5: 1767
Number of records where len >= 6: 0
Number of records where len == 1: 577
Number of records where len == 2: 557
Number of records where len == 3: 645
Number of records where len == 4: 814
Number of records where len == 5: 1767
Number of records where len == 6: 0